name: Node.js CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run coverage
# Disabling for now since codaacy-coverage-reporter does not currently support ECMAScript modules
#    - name: codacy-coverage-reporter
#      uses: codacy/codacy-coverage-reporter-action@v1.1.0
#      with:
#        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#        coverage-reports: coverage/cobertura-coverage.xml
