name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194
      - run: npm ci --ignore-scripts
      - run: npm run coverage
#     - name: codacy-coverage-reporter
#       uses: codacy/codacy-coverage-reporter-action@<SHA>
#       with:
#         project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#         coverage-reports: coverage/cobertura-coverage.xml
