name: Publish

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm publish
